name: cittamobi-forecast
channels:
  - conda-forge
dependencies:
  - python=3.12
  - numpy=1.26.4
  - pandas=2.2.2
  - scipy=1.11.4
  - scikit-learn=1.4.2
  - statsmodels=0.14.2
  - matplotlib=3.8.4
  - pip
  - geopy
  - lightgbm
  - holidays
  - ipykernel
  - xgboost
  - seaborn
